# Generated by Django 4.1.1 on 2022-10-11 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='검사기관')),
            ],
        ),
        migrations.CreateModel(
            name='ModelType',
            fields=[
                ('model', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='모델명')),
                ('type', models.CharField(choices=[('S', 'Single'), ('T', 'Twin')], max_length=200, verbose_name='제품 타입')),
                ('load_weight', models.IntegerField(default=0, verbose_name='적재하중')),
                ('operation_section', models.IntegerField(default=0, verbose_name='운행구간')),
                ('capacity', models.IntegerField(default=0, verbose_name='최대정원')),
                ('rated_speed', models.IntegerField(default=0, verbose_name='정격속도')),
            ],
            options={
                'db_table': 'modeltype',
                'ordering': ['model'],
            },
        ),
        migrations.CreateModel(
            name='Parts',
            fields=[
                ('serial', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='시리얼')),
                ('production_date', models.DateField(verbose_name='제조일')),
                ('discard_date', models.DateField(verbose_name='폐기일')),
            ],
            options={
                'db_table': 'parts',
                'ordering': ['serial', 'production_date'],
            },
        ),
        migrations.CreateModel(
            name='PartsType',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name='부품명')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('serial', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='리프트 번호')),
                ('production_date', models.DateField(verbose_name='제조일')),
                ('discard_date', models.DateField(verbose_name='폐기일')),
                ('model', models.ForeignKey(blank=True, db_column='model_type', null=True, on_delete=django.db.models.deletion.CASCADE, to='item_log.modeltype', verbose_name='모델명')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductionCompany',
            fields=[
                ('business_number', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True, verbose_name='사업자번호')),
                ('name', models.CharField(max_length=400, verbose_name='제조사명')),
                ('ceo', models.CharField(max_length=100, verbose_name='대표')),
                ('address', models.CharField(max_length=1000, verbose_name='주소')),
                ('phone', models.CharField(max_length=100, verbose_name='전화번호')),
                ('insureance_company', models.CharField(max_length=200, verbose_name='보험사명')),
                ('insureance', models.CharField(max_length=200, verbose_name='보험상품명')),
                ('start_date', models.DateField(verbose_name='보험기간 시작일')),
                ('end_date', models.DateField(verbose_name='보장기간 종료시점')),
            ],
            options={
                'db_table': 'production_company',
                'ordering': ['business_number'],
            },
        ),
        migrations.CreateModel(
            name='Break',
            fields=[
                ('break_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_log.parts', verbose_name='브레이크 시리얼')),
                ('torque', models.FloatField(verbose_name='토크')),
            ],
            options={
                'db_table': 'breaks',
                'ordering': ['break_id'],
            },
            bases=('item_log.parts',),
        ),
        migrations.CreateModel(
            name='Motor',
            fields=[
                ('motor_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_log.parts', verbose_name='모터 시리얼')),
                ('capacity', models.FloatField(verbose_name='용량')),
            ],
            options={
                'db_table': 'motor',
                'ordering': ['motor_id'],
            },
            bases=('item_log.parts',),
        ),
        migrations.CreateModel(
            name='Reducer',
            fields=[
                ('recuder_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_log.parts', verbose_name='감속기 시리얼')),
                ('gear_ratio', models.FloatField(verbose_name='감속비')),
            ],
            options={
                'db_table': 'reducers',
                'ordering': ['recuder_id'],
            },
            bases=('item_log.parts',),
        ),
        migrations.CreateModel(
            name='SafetyDevice',
            fields=[
                ('safety_device_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='item_log.parts', verbose_name='가바나 시리얼')),
                ('capacity', models.FloatField(verbose_name='용량')),
            ],
            options={
                'db_table': 'safety_devices',
                'ordering': ['safety_device_id'],
            },
            bases=('item_log.parts',),
        ),
        migrations.CreateModel(
            name='SelfDiagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='점검업체')),
                ('checker', models.CharField(blank=True, max_length=200, null=True, verbose_name='점검자')),
                ('date', models.DateField(verbose_name='점검일자')),
                ('result', models.CharField(blank=True, choices=[('합', '적합'), ('불', '부적합')], max_length=200, null=True, verbose_name='자체점검결과')),
                ('check_list', models.CharField(blank=True, choices=[('제출', '제출'), ('미제출', '미제출')], max_length=200, null=True, verbose_name='점검표')),
                ('product', models.ForeignKey(db_column='product_serial', on_delete=django.db.models.deletion.CASCADE, to='item_log.product', verbose_name='리프트 번호')),
            ],
            options={
                'db_table': 'self_diagnosis',
                'ordering': ['date', 'product'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='production_company',
            field=models.ForeignKey(blank=True, db_column='production_company_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='item_log.productioncompany', verbose_name='제조업체'),
        ),
        migrations.AddField(
            model_name='parts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_log.partstype', verbose_name='부품명'),
        ),
        migrations.AddField(
            model_name='parts',
            name='model_serial',
            field=models.ForeignKey(blank=True, db_column='model_serial', null=True, on_delete=django.db.models.deletion.CASCADE, to='item_log.product', verbose_name='리프트 번호'),
        ),
        migrations.CreateModel(
            name='FaultHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_type', models.TextField(verbose_name='고장유형')),
                ('date', models.DateField(verbose_name='고장일')),
                ('cause', models.TextField(verbose_name='고장원인')),
                ('repair_company', models.TextField(verbose_name='구출기관')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_log.parts', verbose_name='부품 시리얼')),
            ],
            options={
                'db_table': 'fault_history',
                'ordering': ['date', 'parts'],
            },
        ),
        migrations.CreateModel(
            name='CheckHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.TextField(verbose_name='검사종류')),
                ('date', models.DateField(verbose_name='검사일')),
                ('effective_duration', models.TextField(verbose_name='운행유효기관')),
                ('inspection_agency', models.TextField(verbose_name='검사기관')),
                ('inspector', models.CharField(blank=True, max_length=100, null=True, verbose_name='검사원')),
                ('result', models.CharField(choices=[('합', '적합'), ('부', '부적합')], max_length=100, verbose_name='합격유무')),
                ('parts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_log.parts', verbose_name='부품 시리얼')),
            ],
            options={
                'db_table': 'check_history',
                'ordering': ['date', 'parts'],
            },
        ),
    ]
