# Generated by Django 4.1.1 on 2022-10-02 09:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phoneNumber', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='잘못 된 형식의 연락처를 입력했습니다.', regex='^01([0|1|6|7|8|9]?)-?([0-9]{3,4})-?([0-9]{4})$')])),
                ('address', models.CharField(max_length=1000)),
                ('ceo_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('category_name', models.CharField(max_length=200)),
                ('production_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='SalesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_date', models.DateTimeField(verbose_name='date of sales')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_log.buyer')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_log.item')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateTimeField(verbose_name='date published')),
                ('log', models.CharField(max_length=5000)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='item_log.item')),
            ],
        ),
    ]
