# Generated by Django 4.1.1 on 2022-10-13 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkhistory',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='검사일'),
        ),
        migrations.AlterField(
            model_name='checkhistory',
            name='effective_duration',
            field=models.TextField(blank=True, null=True, verbose_name='운행유효기관'),
        ),
        migrations.AlterField(
            model_name='checkhistory',
            name='inspection_agency',
            field=models.TextField(blank=True, null=True, verbose_name='검사기관'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='discard_date',
            field=models.DateField(blank=True, null=True, verbose_name='폐기일'),
        ),
        migrations.AlterField(
            model_name='parts',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='제조일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='discard_date',
            field=models.DateField(blank=True, null=True, verbose_name='폐기일'),
        ),
        migrations.AlterField(
            model_name='product',
            name='production_date',
            field=models.DateField(blank=True, null=True, verbose_name='제조일'),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='보장기간 종료시점'),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='보험기간 시작일'),
        ),
        migrations.AlterField(
            model_name='selfdiagnosis',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='점검일자'),
        ),
    ]
