# Generated by Django 4.1.1 on 2022-10-13 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_log', '0002_alter_checkhistory_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkhistory',
            name='check_type',
            field=models.CharField(max_length=200, verbose_name='검사종류'),
        ),
        migrations.AlterField(
            model_name='checkhistory',
            name='effective_duration',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='운행유효기간'),
        ),
        migrations.AlterField(
            model_name='checkhistory',
            name='inspection_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='item_log.checkcompany', verbose_name='검사기관'),
        ),
        migrations.AlterField(
            model_name='faulthistory',
            name='repair_company',
            field=models.CharField(max_length=200, verbose_name='구출기관'),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='insureance',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='보험상품명'),
        ),
        migrations.AlterField(
            model_name='productioncompany',
            name='insureance_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='보험사명'),
        ),
    ]
