# Generated by Django 4.1.1 on 2022-10-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_log', '0003_alter_checkhistory_check_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkhistory',
            name='inspection_agency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='item_log.checkcompany', verbose_name='검사기관'),
        ),
    ]
