# Generated by Django 4.1.1 on 2022-10-13 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_log', '0004_alter_checkhistory_inspection_agency'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkcompany',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelTable(
            name='checkcompany',
            table='check_company',
        ),
    ]
