# Generated by Django 4.1.1 on 2022-10-13 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item_log', '0005_alter_checkcompany_options_alter_checkcompany_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=400, verbose_name='현장명')),
                ('num_floors', models.IntegerField(blank=True, null=True, verbose_name='지상층')),
                ('num_basements', models.IntegerField(blank=True, null=True, verbose_name='지하층')),
                ('instalation_date', models.DateField(blank=True, null=True, verbose_name='설치일/최초설치일')),
                ('next_check_date', models.DateField(blank=True, null=True, verbose_name='정밀안전검사예정일')),
                ('withdrawal_date', models.DateField(blank=True, null=True, verbose_name='철거예정일')),
                ('safety_checker', models.CharField(max_length=200, verbose_name='안전관리자')),
                ('safety_checker_phone', models.CharField(max_length=200, verbose_name='안전관리자 연락처')),
                ('safety_edu_comp_date', models.DateField(blank=True, null=True, verbose_name='안전교육 이수일')),
                ('management_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='유지관리업체')),
                ('management_comp_phone', models.CharField(max_length=200, verbose_name='유지관리업체 연락처')),
                ('subcontract_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='하도급/공동수급업체')),
                ('subcontract_comp_phone', models.CharField(max_length=200, verbose_name='하도급/공동수급업체 연락처')),
            ],
            options={
                'db_table': 'contract',
                'ordering': ['instalation_date', 'product', 'part'],
            },
        ),
        migrations.AlterModelOptions(
            name='checkhistory',
            options={'ordering': ['date', 'product', 'part']},
        ),
        migrations.RemoveField(
            model_name='checkhistory',
            name='parts',
        ),
        migrations.AddField(
            model_name='checkhistory',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_log.parts', verbose_name='부품 시리얼'),
        ),
        migrations.AddField(
            model_name='checkhistory',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_log.product', verbose_name='제품 시리얼'),
        ),
        migrations.AddConstraint(
            model_name='checkhistory',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('part__isnull', True), ('product__isnull', False)), models.Q(('part__isnull', False), ('product__isnull', True)), _connector='OR'), name='item_log_checkhistory_part_or_product'),
        ),
        migrations.AddField(
            model_name='contract',
            name='part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_log.parts', verbose_name='부품 시리얼'),
        ),
        migrations.AddField(
            model_name='contract',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='item_log.product', verbose_name='제품 시리얼'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('part__isnull', True), ('product__isnull', False)), models.Q(('part__isnull', False), ('product__isnull', True)), _connector='OR'), name='item_log_contract_part_or_product'),
        ),
    ]
