# Generated by Django 4.1.1 on 2022-10-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_log', '0006_contract_alter_checkhistory_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='test_td',
            field=models.IntegerField(default=0, verbose_name='시험'),
        ),
    ]
