# Generated by Django 4.1.1 on 2022-10-17 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_log', '0007_contract_test_td'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='test_td',
        ),
        migrations.AlterField(
            model_name='contract',
            name='management_comp_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='유지관리업체 연락처'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='safety_checker',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='안전관리자'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='safety_checker_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='안전관리자 연락처'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='subcontract_comp_phone',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='하도급/공동수급업체 연락처'),
        ),
    ]
