version: "3.7"
services:
  nginx:                 
    container_name: nginx
    restart: on-failure
    image: nginx:stable
    volumes:
      - ${PWD}/etc/jnbdrive_nginx:/etc/nginx/sites-enabled/default
      - ${PWD}/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/etc/proxy_params:/etc/nginx/proxy_params
      - ${PWD}/staticfiles:/home/nginx/www/static
       
    ports:
      - 80:80
    depends_on:
      - jnb_web
    networks:
      - backend

  jnb_web:
    container_name: jnb_web
    build: .
    image: jnb_ap:latest
    ports:
      - 8000:8000
    restart: always
    environment:
      DB_PORT: 3306
      DB_HOST_ADDRESS: jnbdrive-product.cie6ndifnblb.ap-northeast-2.rds.amazonaws.com
    volumes: 
      - ${PWD}:/home/docker/workspace/jnbdrive_app
    networks:
      - backend

    command: gunicorn --workers 1 --bind 0.0.0.0:8000 config.wsgi:application 

networks:
  backend:
    # Use a custom driver
    driver: bridge
