version: "3.7"
services:
  nginx:                 
    container_name: nginx
    restart: on-failure
    image: nginx:stable
    volumes:
      - ${PWD}/etc/jnbdrive_nginx:/etc/nginx/sites-enabled/default
      - ${PWD}/etc/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${PWD}/etc/proxy_params:/etc/nginx/proxy_params
      - ${PWD}/staticfiles:/home/nginx/www/static
       
    ports:
      - 80:80
      - 443:443
    environment:
      DJANGO_HOST: jnb_web
    depends_on:
      - jnb_web

  mysql:
    container_name: mysql
    image: mysql:8.0.31
    ports:
      - 3306:3306 
    volumes:
      - ${HOME}/jnbdrive_disk:/var/lib/mysql # change it on production env
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: Gotobali1! # change it on production env
      MYSQL_USER: jnb # change it on production env
      MYSQL_PASSWORD: jnbdrive-0922 # change it on production env
      MYSQL_DATABASE: jnbdrive # change it on production env
    networks:
      - backend

  jnb_web:
    container_name: jnb_web
    depends_on:
      - mysql
    build: .
    image: jnb_app:latest
    ports:
      - 8000:8000
    restart: always
    environment:
      DB_PORT: 3306
      DB_HOST_ADDRESS: mysql
    volumes: 
      - ${PWD}:/home/docker/workspace/jnbdrive_app
    networks:
      - backend

    command: gunicorn --workers 2 --bind 0.0.0.0:8000 config.wsgi:application 

networks:
  backend:
    # Use a custom driver
    driver: bridge
